export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"
export const RELOAD = "RELOAD"
export const TEACHER_INFO = "TEACHER_INFO"
export const GET_STUDENTS = "GET_STUDENTS"
export const GET_ONE_STUDENT = "GET_ONE_STUDENT"
export const GET_GROUPS = "GET_GROUPS"
export const GET_TEACHERS = "GET_TEACHERS"